# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Set default Provider to be VirtualBox
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  # Use Ubuntu VirtualBox
  config.vm.box = "ubuntu/focal64"

  # PostgreSQL
  config.vm.network "forwarded_port", guest: 5432, host: 8000

  # Installations and Configurations
  config.vm.provision :shell, path: "./bootstrap.sh"
  
end
